### ISSUE TITLE
Missing l1_handler on AbiType leads to type errors

### ISSUE THREAD

**Issue by edulanasca** [Quantum3-Labs/scaffold-stark-2#177]
## Issue Overview

when declaring l1_handler functions on cairo contracts, this will appear on the abi and are not taken into consideration as a regular `type Abi`

## Proposed Solutions or Ideas

- implement a custom `type Abi` to avoid type errors
- check and update `abi-wan-kanabi` dep 

### Instructions for Contributing

- Leave a comment on this Issue.
- Wait for our confirmation to start on the project.
- Once you have received confirmation, begin working on your contribution.

### Incentives

Contributions are rewarded via Only Dust.

### Contact

For questions, join to our [tg group](https://t.me/+wO3PtlRAreo4MDI9) and reach out our team

**Comment by od-hunter** [comment]
Can I be assigned this please?

**Comment by od-hunter** [comment]
What does external contributor mean?

**Comment by nemealfaro** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hi, I'm Nemesis Alfaro from Costa Rica, i'm a system engineer.
I love  to learn and practice about different tecnologies.
I'm hard-working, constant and curious person
This would be my first contribution on the platform, in order to gain more knowledge and improve in the area.


### How I plan on tackling this issue
I would like carefully read the request and be in  contact with you for more infomation.
Then i would to further investigate about the options to solve the issue and do tests, in case of presenting problems to do this, i would like to be in contact with you to provide me more details about the problem
