### ISSUE TITLE
Remove support for Goerli Network

### ISSUE THREAD

**Issue by gianalarcon** [Quantum3-Labs/scaffold-stark-2#186]
## Issue Overview

Currently the framework still shows support for `Goerli` Network.

## Proposed Solutions or Ideas

Clean and remove everything related to `Goerli` testnet without affecting the current performance of framework on devnet or testnet. It could include entire files that the framework is not using anymore.

### Instructions for Contributing

- Leave a comment on this Issue.
- Wait for our confirmation to start on the project.
- Once you have received confirmation, begin working on your contribution.

### Incentives

Contributions are rewarded via Only Dust.

### Contact

For questions, join to our [tg group](https://t.me/+wO3PtlRAreo4MDI9) and reach out our team

**Comment by DilanHern** [comment]
Hello, my name is Dilan. I would like to work on this issue if it's possible. I´ve been working with js and ts so i should be able to complete the task, thanks :)

**Comment by TAdev0** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Engineer at Nethermind working on the Cairo VM in Go
I am 34th on OnlyDust, contributed to many OS projects


### How I plan on tackling this issue
I would basically follow instructions, i.e., remove everything related to goerli network which is deprecated since april

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged

Hello Project Lead! I'm Ugo, a fullstack(js,React,Node,Next.js,Three.js) developer with a strong track record in OD hack projects. I've been actively involved since Edition 1, contributing to various initiatives.
Having used OnlyDust extensively , I'm confident in my ability to tackle new challenges.
I'm eager to leverage my skills and experience to contribute effectively.

**Comment by gianalarcon** [comment]
Thanks all of you guys for showing your interest. This time will the chance to @Ugo-X. Please @Ugo-X  check again the issue and send your PR during the upcoming days.

**Comment by Ugo-X** [comment]
> Thanks all of you guys for showing your interest. This time will the chance to @Ugo-X. Please @Ugo-X check again the issue and send your PR during the upcoming days.

Good morning chief. Thank you, I'll get to it and be sure to keep you updated. Please is there a Telegram group? for easier communication.

**Comment by gianalarcon** [comment]
> > Thanks all of you guys for showing your interest. This time will the chance to @Ugo-X. Please @Ugo-X check again the issue and send your PR during the upcoming days.
> 
> Good morning chief. Thank you, I'll get to it and be sure to keep you updated. Please is there a Telegram group? for easier communication.

We provided the tg group info in the description of the issue...

**Comment by Ugo-X** [comment]
oh my bad, thanks.
