### ISSUE TITLE
Add script to reset deployments `yarn deploy:reset`

### ISSUE THREAD

**Issue by 0xquantum3labs** [Quantum3-Labs/scaffold-stark-2#209]
## Issue Overview

We need to allow users to keep previously deployed contracts that are stored locally after each deployment. 
The idea is to have the current `yarn deploy` to  not override the `latest` deployment but rather append contracts to it.

Add another script to do `yarn deploy:reset` which will do what `yarn:deploy` currently does. Reset all the contracts deployed that are exported to `packages/nextjs` to be only the contracts deployed on the last RUN.

## Proposed Solutions or Ideas

- should change the `package.json` on source folder and snfoundry package
- check that this works on devnet since devnet is usually started from zero, add an error message on missing contract declaration on UI. should tell you to run `yarn deploy:reset` if the contract inside `/debug` page doesnt exist

**Comment by adrianvrj** [comment]
hi, can I work on this?

**Comment by raizo07** [comment]
@0xquantum3labs I'll like to work on this

**Comment by josephchimebuka** [comment]
I would like to handle this

**Comment by Nadai2010** [comment]
Hi everyone, @adrianvrj @raizo07 and @josephchimebuka we are preparing the issues for tomorrow's OD Hach, they will be assigned tomorrow

Remember that you can only work on one issue at a time, choose well

**Comment by adrianvrj** [comment]
> Hi everyone, @adrianvrj @raizo07 and @josephchimebuka we are preparing the issues for tomorrow's OD Hach, they will be assigned tomorrow
> 
> 
> 
> Remember that you can only work on one issue at a time, choose well

nice, just let me know if I can work on this tomorrow! really excited to contribute to this project

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
As an experienced analyst and blockchain developer with 15 years in the industry. i  likely encountered a variety of challenges that these technologies can help address. My technical expertise and problem-solving skills will be valuable assets in leveraging JavaScript, Cairo, and TypeScript.

### How I plan on tackling this issue
Add yarn deploy:reset Script
Update package.json in source and @scaffold-stark/contracts:
Add "deploy:reset": "hardhat run --network devnet scripts/deploy.ts".
Modify deploy.ts:
Read existing deployments, merge with new ones, and update deployments.json.
Update deploy script:
Change to use deploy:reset instead of the original deploy script.
Handle Missing Contracts on UI:
Check if contract address exists in deployments.json.
Display error and suggest running yarn deploy:reset.

**Comment by SebastianLF** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am a seasoned developer with extensive experience in TypeScript and JavaScript. I have a strong background in developing and maintaining web applications, and I have worked on various projects that involve smart contracts and blockchain technology. My experience with bounties on the Gitcoin platform has honed my skills in quickly understanding and addressing specific issues, collaborating with teams, and delivering high-quality solutions.

### How I plan on tackling this issue
To address the issue of adding a yarn deploy:reset script, I would follow these steps:

1. Understand the Current Deployment Process:

. Review the existing deployment script to understand how contracts are currently deployed and stored.
. Identify the parts of the script that need to be modified to append new contracts instead of overriding them.

2. Modify the Deployment Script:

. Change the logic in the deployment script to append new contracts to the existing deployment.
. Ensure that the changes are made in a way that maintains the integrity of the deployment process.

3. Create the Reset Script:

. Develop a new script (deployReset.js) that resets the deployment to the last run.
. This script should deploy new contracts and overwrite the existing deployment file with the new contracts.

4. Update package.json:

. Add the new script to the scripts section in package.json to make it accessible via yarn deploy:reset.

5. Test on Devnet:

. Test the modified deployment script and the new reset script on the devnet environment.
. Ensure that the scripts work as expected and handle edge cases gracefully.

6. Add Error Handling and UI Messages:

. Modify the UI code to check for missing contracts and display an appropriate error message.
. Suggest running yarn deploy:reset if a contract is missing.

7. Documentation and Testing:

. Update any relevant documentation to reflect the changes made.
. Conduct thorough testing to ensure that the deployment process appends contracts correctly and that the reset script works as expected.

**Comment by ShantelPeters** [comment]
Hi , can I be assigned to this issue

**Comment by Nadai2010** [comment]
Hi @josephchimebuka, we remind you that you must upload your PR or comments in order to continue with the assigned issue.

**Comment by josephchimebuka** [comment]
Hello @Nadai2010 I made some changes already on my forked repo I will make a PR soon... Thanks!

**Comment by 0xquantum3labs** [comment]
hi @josephchimebuka any updates on this ?

**Comment by josephchimebuka** [comment]
Hello @0xquantum3labs almost done you'll get a PR from me today!
