### ISSUE TITLE
Add contract verification script

### ISSUE THREAD

**Issue by 0xquantum3labs** [Quantum3-Labs/scaffold-stark-2#210]
## Issue Overview

Add a script `yarn deploy:verify` that verifies contracts to a explorer, either `starkscan` or `voyager`

## Proposed Solutions or Ideas

- should change `package.json` on source and foundry package.

**Comment by danielcdz** [comment]
Hello! Couple of weeks ago I contributed to this project, I'm working wondering if I can help with this issue during the ODHack!

**Comment by Nadai2010** [comment]
Hi everyone, @danielcdz we are preparing the issues for tomorrow's OD Hach, they will be assigned tomorrow

Remember that you can only work on one issue at a time, choose well

**Comment by danielcdz** [comment]
For sure @Nadai2010 I'm very interested on this one, I'll wait, thank you for the opportunity

**Comment by ktarun1419** [comment]
Hi @danielcdz  can i work on this issue ?

**Comment by zarah-s** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
With my strong background in Rust, Solidity and JavaScript, I can apply my expertise in solving this issue

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust](https://app.onlydust.com/p/speedrun-scaffold-stark)ll

_Background and Leverage:_
As a frontend developer with experience in building interactive UI components and API integrations, I've developed strong problem-solving skills and attention to detail. My background in smart contract development and deployment has equipped me with the skills to verify contracts on explorers like StarkScan and Voyager.

_Approach to the Problem:_

1. _Research and Choose Explorer API:_ I'll research and choose the most suitable explorer API (StarkScan or Voyager) for contract verification.
2. _Create yarn deploy:verify Script:_ I'll create a new script in package.json to run the verification process.
3. _Implement Verification Logic:_ I'll write the logic to verify contracts using the chosen explorer API.
4. _Update package.json:_ I'll update package.json in both the source and foundry packages to include the new script.
5. _Test and Refine:_ I'll thoroughly test the verification process and refine it as needed.

_Solution:_
My proposed solution involves creating a new yarn script, implementing verification logic, and updating package.json files.

_Technical Details:_

- I'll use JavaScript and Node.js to create the verification script.
- I'll utilize the explorer API's documentation to ensure accurate implementation.
- I'll ensure the script is modular, reusable, and easy to maintain.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hello Project Lead! I'm Ugo, a fullstack(js,React,Node,Next.js,Three.js) developer with a strong track record in OD hack projects. I've been actively involved since Edition 1, contributing to various initiatives, and I'm thrilled to be part of Edition 6!
Having used OnlyDust extensively (see my profile: https://app.onlydust.com/u/Ugo-X)), I'm confident in my ability to tackle new challenges within this edition.
I'm eager to leverage my skills and experience to contribute effectively.

### How I plan on tackling this issue

To solve issue #216

I would update the versions of all scaffold stark dependencies to support starknet-react:next.

I would update the rpc configuration to support v0.7.1

I would also update the snfoundry package and the workflow file to support the starknet latest release.

**Comment by bitfalt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I've done some projects using Cairo and developing on Starknet, so I'm familiar with both block explorers. I've also used Typescript/Javascript in many web2 projects due to University. Due to the reasons mentioned before, I feel confident I could tackle this issue.

### How I plan on tackling this issue
I would approach the problem in the following way:
- Research about the API for both block explorers
- Given the results of my research, I would pick the best block explorer API given the specifications
- Add the proper script to verify the contracts in the picked block explorer.
- Modify the package.json file accordingly

**Comment by Ugo-X** [comment]
Thanks, I will get to it and be sure to relay updates.

**Comment by Nadai2010** [comment]
Hi @Ugo-X , we remind you that you must upload your PR or comments in order to continue with the assigned issue.

**Comment by Ugo-X** [comment]
> Hi @Ugo-X , we remind you that you must upload your PR or comments in order to continue with the assigned issue.

Hey @Nadai2010  sure thing! will put out a PR for review today, almost done.

**Comment by Nadai2010** [comment]
Thank you very much @Ugo-X

**Comment by Ugo-X** [comment]
@Nadai2010 Good morning, still need a little time, I am currently testing.

**Comment by Ugo-X** [comment]
@0xquantum3labs @Nadai2010 @jrcarlos2000 
Can the verify deploy be a function in the deploy contract.ts which will check for when a contract is deployed and then verify it by sending a request to the Starknet API or must it be a script in the snfoundry package.json which must be called on the terminal to verify the deployment?

**Comment by bitfalt** [comment]
Hiii! I was wondering if this issue is still available for contributors. I'd love to help tackle it properly. I understand that when someone deploys a smart contract it should verify it automatically (meaning all the smart contracts in the deploy.ts file), avoiding harcoded values. Any questions I have during the development I would ask one of the maintainers for feedback and guide if I get stuck at any point.

**Comment by gianalarcon** [comment]
Closing for now
